### ISSUE TITLE
当开启对局域网开放其他人进入存档报错

### ISSUE THREAD

**Issue by BrGef** [zly2006/Enclosure#35]
bug
开启对局域网开放其他人无法进入我的存档，即使双方都安装mod也无法进入，只能禁用主机mod才能解决。另外bug仅是客户端无法进入，主机端是没有任何报错，即使客户端没有安装mod也无法进入，只要主机安装即可

触发方法
开启2个客户端一个为主机进存档开启对局域网联机，另一个客户端加入即会报错，与其他人联机也是同样
![9b5825751f7367eff731f6d2f0ff9d02.png](https://github.com/zly2006/Enclosure/assets/101499922/78121844-731a-42c3-81e2-bf05e712b69f)

游戏版本1.20.2
mod版本0.3.5

mod列表
fabric-api-0.91.3+1.20.2.jar
fabric-language-kotlin-1.10.15+kotlin.1.9.21.jar
enclosure-fabric-0.3.5+1.20.jar

**Comment by zly2006** [comment]
能不能上传一下latest.log?

**Comment by BrGef** [comment]
> 能不能上传一下latest.log?

主机的log吗
还是连接的客户端log

**Comment by zly2006** [comment]
最好都要

**Comment by BrGef** [comment]
[主机端latest.log](https://github.com/zly2006/Enclosure/files/13925068/latest.log)
[客户端latest.log](https://github.com/zly2006/Enclosure/files/13925069/latest.log)

**Comment by BrGef** [comment]
> 最好都要

这个bug百分之百触发的，开两个游戏，一个开存档，一个进存档就是这样，进存档的怎么查都没用

**Comment by zly2006** [comment]
请确认一下是否已经修复

**Comment by BrGef** [comment]
> 请确认一下是否已经修复

问题还是有，你没更新到modrinth吗

**Comment by zly2006** [comment]
> 问题还是有，你没更新到modrinth吗

没有，在[GitHub actions](https://github.com/zly2006/Enclosure/actions/runs/7518499022/)下载最新版，测试修复之后我才后更新到modrinth

**Comment by BrGef** [comment]
> > 问题还是有，你没更新到modrinth吗
> 
> 没有，在[GitHub actions](https://github.com/zly2006/Enclosure/actions/runs/7518499022/)下载最新版，测试修复之后我才后更新到modrinth
> 问题还是一样的

**Comment by BrGef** [comment]
> > 问题还是有，你没更新到modrinth吗
> 
> 没有，在[GitHub actions](https://github.com/zly2006/Enclosure/actions/runs/7518499022/)下载最新版，测试修复之后我才后更新到modrinth
> 


问题还是一样

**Comment by zly2006** [comment]
这不是已经修了吗，你到底真的测过没有，将会发布一个正式版进行修复

**Comment by BrGef** [comment]
> 这不是已经修了吗,你到底真的测过没有,将会发布一个正式版进行修复

我是下载的这个下面包https://github.com/zly2006/Enclosure/actions/runs/7518499022/
是sources还是不带sources
不带的还是一样的，主机开游戏客户端加入还是报错

不带sources我这边启动游戏报错
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod enclosure
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512)
	... 3 more

**Comment by zly2006** [comment]
去试试modrinth版本，还有bug请报告，谢谢

**Comment by BrGef** [comment]
> 去试试modrinth版本，还有bug请报告，谢谢

ok
